name: 自动部署

on:
  push:
    branches: [ hexo-source ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 安装依赖
        run: |
          npm config set registry https://registry.npmmirror.com
          npm ci

      - name: 生成网站
        run: |
          npx hexo clean
          npx hexo generate

      - name: 部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 使用 GitHub 自动提供的令牌，无需任何额外配置
          github_token: ${{ secrets.HEXO_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: main
          commit_message: '自动部署: ${{ github.sha }}'
